export const navLinks = [
  { name: "Home", path: "/" },
  {
    name: "Services",
    path: "/service",
    submenu: [
      { name: "Healthcare", path: "/services/healthcare", description: "Tailored IT solutions for the healthcare sector." },
      { name: "Banking & Financial", path: "/services/banking-financial", description: "Secure and compliant financial technology services." },
      { name: "Media & Entertainment", path: "/services/media-entertainment", description: "Engaging digital experiences for media companies." },
      { name: "Technology Enablement", path: "/services/technology-enablement", description: "Modernizing your business with the latest tech." },
      { name: "Strategic Staffing", path: "/services/strategic-staffing", description: "Finding the right talent for your IT needs." },
      { name: "Business Process Outsourcing", path: "/services/business-process-outsourcing", description: "Optimizing your business operations." },
      { name: "Recruitment Process Outsourcing", path: "/services/recruitment-process-outsourcing", description: "Streamlining your recruitment lifecycle." },
      { name: "Training Hub", path: "/services/training-hub", description: "Upskilling your workforce for the future." },
    ],
  },
  {
    name: "Industries",
    path: "/industry",
    submenu: [
      { name: "Financial Services", path: "/industries/financial-services", description: "Innovative solutions for the finance industry." },
      { name: "Healthcare", path: "/industries/healthcare", description: "Transforming healthcare with technology." },
      { name: "Media, Entertainment & Gaming", path: "/industries/media-entertainment-gaming", description: "Captivating audiences with immersive tech." },
      { name: "Energy", path: "/industries/energy", description: "Powering the future with sustainable IT." },
      { name: "Telecommunication", path: "/industries/telecommunication", description: "Connecting the world with advanced networks." },
      { name: "Consumer & Industrial Products", path: "/industries/consumer-industrial-products", description: "Driving efficiency from factory to consumer." },
      { name: "Technology Enablement", path: "/industries/technology-enablement", description: "Your partner in digital transformation." },
      { name: "Transportation & Travel", path: "/industries/transportation-travel", description: "Modernizing the way the world moves." },
    ],
  },
  {
    name: "Technologies",
    path: "/technology",
    submenu: [
      { name: "AI & Machine Learning", path: "/technologies/ai-machine-learning" },
      { name: "Cloud Computing", path: "/technologies/cloud-computing" },
      { name: "DevOps", path: "/technologies/devops" },
      { name: "Big Data Technology", path: "/technologies/big-data" },
      { name: "Web Development", path: "/technologies/web-development" },
      { name: "IoT", path: "/technologies/iot" },
      { name: "Android Development", path: "/technologies/android-development" },
      { name: "Java/Python Full Stack", path: "/technologies/java-python-fullstack" },
      { name: "ServiceNow", path: "/technologies/servicenow" },
      { name: "Business/Data Analyst", path: "/technologies/business-data-analyst" },
      { name: "QA Engineer", path: "/technologies/qa-engineer" },
      { name: "Data Science", path: "/technologies/data-science" },
      { name: "Salesforce", path: "/technologies/salesforce" },
    ],
  },
  { name: "Clients", path: "/client" },
  { name: "About", path: "/about" },
  { name: "Careers", path: "/career" },
  { name: "Contact", path: "/contact" },
];
